name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Configure git user (for commits in workflow)
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Ensure gh-pages branch exists (first-time init)
        run: |
          set -e
          if ! git ls-remote --exit-code --heads origin gh-pages; then
            git fetch origin
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "init gh-pages"
            git push origin gh-pages
            git checkout main
          fi

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to gh-pages
        env:
          GIT_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEPLOYMENT_BRANCH: gh-pages
        run: npm run deploy


